#!/usr/bin/env python 
from __future__ import print_function, division
import sys
sys.dont_write_bytecode = True

"""

# Markdown to Html

+ Generate and print Html

"""
import sys,markdown2,os

def marked(s):
  return markdown2.markdown(s,
           ["metadata",
            "fenced-code-blocks",
            "footnotes",
            "toc"])

def contents(f):
  with open(f, "r") as str:
     txt=str.read()
  return txt
"""

Output

"""
print(marked(''.join(sys.stdin.readlines())))
