#!/bin/bash

if [ -f "HEADER.html" ]; then
   cat HEADER.html -
elif [ -f "$1/../HEADER.html" ]; then
   cat $1/../HEADER.html -
fi  |
gawk '

/<h1/ { str = $0
         gsub(/h1/,"title",str)
       }
       { out = out "\n" $0 }
END    { gsub(/<title>[^<\n]*<\/title>/,str,out)
         print out}
'

if [ -f "FOOTER.html" ]; then
   cat FOOTER.html
fi


